beraca/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('core.urls', namespace="core")),
]
# urlpatterns += i18n_patterns(
#     url(r'', include('core.urls', namespace="core")),
#     prefix_default_language=False,
# )

core/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import settings
from . import views
from django.views.generic.base import TemplateView

from django.contrib.sitemaps.views import sitemap

from core.views import AboutInternalView, ProjectView

from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^about/$', views.AboutInternalView.as_view(), name='about'),
    url(r'^apoieumprojeto/$', views.ProjectView.as_view(), name='project'),
    url(r'^cases/$', views.CasesView.as_view(), name='cases'),
    url(r'^cases/detail/(?P<pk>\d+)$', views.CaseDetailView.as_view(), name='detail'),
    url(r'^blog/$', views.BlogListView.as_view(), name='blog'),
    url(r'^blog/detail/(?P<pk>\d+)$', views.BlogDetailView.as_view(), name='post_detail'),
    url(r'^services/detail/(?P<pk>\d+)$', views.ServiceDetailView.as_view(), name='service_detail'),
    url(r'^robots.txt', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from ckeditor.fields import RichTextField

class Fullwidth_slider_item(models.Model):
    first_phrase = models.CharField("Primeira frase (menor)", max_length=50, blank=False)
    second_phrase = models.CharField("Segunda frase (em destaque)", max_length=50, blank=False)
    slide_image = models.ImageField("Imagem do slide", upload_to='slide_item/%Y/%m/%d/', blank=False)

    def __unicode__(self):
        return self.first_phrase+" "+self.second_phrase

    class Meta:
        verbose_name = "Slide"
        verbose_name_plural = "Slides"

def generate_filename_miniature(self, filename):
    url = "Cases/miniaturas/%s/%s" % (self.title, filename)
    return url

class PortfolioItem(models.Model):
    #common

    title = models.CharField("Título", max_length=300, blank=False)
    sub_title = models.CharField("Subtítulo", max_length=300, blank=False)

    study = models.TextField('Estudo do caso', blank=True)
    results = models.TextField("Resultado", blank=True)
    experience = models.TextField("Experiência", blank=True)

    client = models.CharField("Cliente", max_length=300, blank=False)
    date = models.DateField(auto_now=True)
    online = models.CharField("URL do cliente", max_length=500, blank=True)

    #miniature
    miniature = models.ImageField("Miniatura", upload_to=generate_filename_miniature, blank=False)
    tag = models.CharField("Tag para filtro", max_length=300, blank=False)
    lat = models.CharField("Latitude", max_length=100, blank=True)
    lon = models.CharField("Longitude", max_length=100, blank=True)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = PortfolioItem.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = PortfolioItem.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Portfolio/case"
        verbose_name_plural="Cases"
        ordering = ['-date']

def generate_filename(self, filename):
    url = "Portfolio/%s/%s" % (self.portfolio.title, filename)
    return url

class PortfolioImages(models.Model):
    portfolio = models.ForeignKey(PortfolioItem, related_name='images')
    image = models.ImageField("Primeira imagem(slide)", upload_to=generate_filename)

    def __unicode__(self):
        return self.portfolio.title

def generate_filename_miniature(self, filename):
    title = self.title[:20]
    url = "Posts/miniaturas/%s/%s" % (title, filename)
    return url

class BlogPost(models.Model):
    #common

    title = models.CharField("Título", max_length=300, blank=False)
    sub_title = models.CharField("Sub-título", max_length=300, blank=False, null=True)
    intro = models.TextField("Introdução", blank=False)
    content = RichTextField("Corpo do texto", blank=False)
    date = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)
    author = models.CharField("Autor", max_length=500, blank=True)

    #miniature
    miniature = models.ImageField("Miniatura", upload_to=generate_filename_miniature, blank=False, max_length=255)
    tag = models.CharField("Tag para filtro", max_length=300, blank=False)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = BlogPost.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = BlogPost.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Blog post"
        verbose_name_plural="Posts"
        ordering = ['-date']

def generate_filename(self, filename):
    title = self.post.title[:20]
    url = "Posts/%s/%s" % (title, filename)
    return url

class BlogImages(models.Model):
    post = models.ForeignKey(BlogPost, related_name='images')
    image = models.ImageField("Imagem", upload_to=generate_filename)

    def __unicode__(self):
        return self.post.title

def generate_filename(self, filename):
    url = "Service/%s/%s" % (self.title, filename)
    return url

class ServiceItem(models.Model):
    #common
    anchor = models.CharField("Âncora/Tab", max_length=300, blank=False)
    icon = models.ImageField("Ícone", upload_to=generate_filename)
    title = models.CharField("Título", max_length=300, blank=False)
    mention = models.TextField('Citação', blank=True)
    author = models.CharField("Autor", max_length=300, blank=False)
    abstract = models.TextField("Conceito", blank=True)
    conclusion = models.TextField("Conclusão", blank=True)
    description = RichTextField("Descrição", blank=True)
    date = models.DateField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = ServiceItem.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = ServiceItem.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Service/case"
        verbose_name_plural="Services"
        ordering = ['-date']


class ServiceIcons(models.Model):
    service = models.ForeignKey(ServiceItem, related_name='icones')
    icon = models.ImageField("Ícone", upload_to=generate_filename, blank=True)
    title = models.CharField("Título", max_length=300, blank=True)

    def __unicode__(self):
        return self.service.title

class ServiceMethod(models.Model):
    method = models.ForeignKey(ServiceItem, related_name='methods')
    image = models.ImageField("Imagem", upload_to=generate_filename, blank=True)
    title = models.CharField("Título", max_length=300, blank=True)
    desc = models.TextField("Descrição", max_length=1500, blank=True)

    def __unicode__(self):
        return self.method.title

class AboutSection(models.Model):
    title = models.CharField("Título", max_length=300, blank=True)
    mention = models.TextField('Citação', blank=True)
    author = models.CharField("Autor", max_length=300, blank=True)
    first_content = RichTextField("Primeiro Paragrafo", blank=True)
    second_content = RichTextField("Segundo Paragrafo", blank=True)

    class Meta:
        verbose_name = "Textos para seção 'Sobre'"
        verbose_name_plural = "Textos para seção 'Sobre'"

    def __unicode__(self):
        return self.title

class AboutInternal(models.Model):
    title = models.CharField("Título da Header", max_length=300, blank=True)
    subtitle = models.CharField("Subtítulo", max_length=300, blank=True)
    title_paragraph = models.CharField("Título do Paragrafo", max_length=300, blank=True)
    content = RichTextField("Descrição Geral", blank=True)
    director = RichTextField("Sobre diretoria", blank=True)
    council = RichTextField("Conselho Gestor", blank=True)
    mission = RichTextField("Missão", blank=True)
    vision = RichTextField("Visão", blank=True)
    values = RichTextField("Valores", blank=True)

    class Meta:
        verbose_name = "Textos para seção interna 'Sobre'"
        verbose_name_plural = "Textos para seção interna 'Sobre'"

    def __unicode__(self):
        return self.title

core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.mail import send_mail, BadHeaderError, EmailMessage
from django.conf import settings
from django.template.loader import get_template
from django.utils.translation import ugettext_lazy as _

class ContactUs(forms.Form):
    name = forms.CharField(required=False,
    widget=forms.TextInput(
    attrs={'class':'input-md round form-control', 'placeholder':_('NOME'), 'pattern':'.{3,100}', 'id':'name'}))

    email = forms.EmailField(required=False,
    widget=forms.TextInput(
        attrs={'class':'input-md round form-control', 'placeholder':'EMAIL', 'pattern':'.{5,100}', 'id':'email'}))

    content = forms.CharField(required=False,
    widget=forms.Textarea(
        attrs={'class':'input-md round form-control height-84', 'placeholder':_('MENSAGEM'), 'id':'message'}))

    def send_email(self):
        email_template = get_template('core/email_template.html')
        name = self.cleaned_data['name']
        from_email = self.cleaned_data['email']
        message = self.cleaned_data['content']
        context = {
            'name': name,
            'email': from_email,
            'message': message
        }
        html_email = email_template.render(context)
        subject = 'Novo Contato'
        try:
            email = EmailMessage(subject, html_email, from_email,[settings.EMAIL_TO])
            email.content_subtype = "html"
            email.send()
        except BadHeaderError:
            raise ValidationError("Cabeçalho inválido")

core/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse
from django.template.loader import get_template
from django.contrib import messages
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from .models import Fullwidth_slider_item, BlogPost, ServiceItem, AboutSection, PortfolioItem, AboutInternal
from .forms import *
import operator
from django.db.models import Q
from django.conf import settings
import urllib
import urllib2
import json
# from django.utils import translation


# Create your views here.
# def fullsite(request):
# 	context_general = {}
# 	return render(request, 'core/index.html', context_general)

class Index(FormView):
	template_name = "core/home.html"
	form_class = ContactUs
	success_url = '/'

	def get_context_data(self, **kwargs):
		context = super(Index, self).get_context_data(**kwargs)
		context.update({
			'slide_itens': Fullwidth_slider_item.objects.all(),
			'posts': BlogPost.objects.all().order_by('-date')[:3],
			'services': ServiceItem.objects.all().order_by('title')[:5],
			'tabs': ServiceItem.objects.all().order_by('-date')[:5],
			'about_section': AboutSection.objects.all(),
		})
		return context

	def form_valid(self, form):
		''' Begin reCAPTCHA validation '''
		recaptcha_response = self.request.POST.get('g-recaptcha-response')
		url = 'https://www.google.com/recaptcha/api/siteverify'
		values = {
			'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
			'response': recaptcha_response
        }
		data = urllib.urlencode(values)
		req = urllib2.Request(url, data)
		response = urllib2.urlopen(req)
		result = json.load(response)
		''' End reCAPTCHA validation '''
		print "hello"
		if result['success']:
			form.send_email()
			messages.success(self.request, 'Seu contato foi enviado com sucesso!')
		else:
			messages.error(self.request, 'reCAPTCHA inválida. Por favor, tente novamente.')

		return super(Index, self).form_valid(form)

	# from django.utils import translation
	# user_language = 'en'
	# translation.activate(user_language)
	# request.session[translation.LANGUAGE_SESSION_KEY] = user_language

	# if translation.LANGUAGE_SESSION_KEY in request.session:
	# 	del request.session[translation.LANGUAGE_SESSION_KEY]

class ProjectView(TemplateView):
    template_name = "core/project.html"

class CasesView(TemplateView):
	template_name = "core/cases.html"

	def get_context_data(self, **kwargs):
		context = super(CasesView, self).get_context_data(**kwargs)
		context.update({
			'cases': PortfolioItem.objects.all(),
		})
		return context

class CaseDetailView(DetailView):
	template_name = "core/detail_templates/case_detail.html"
	model = PortfolioItem


class BlogListView(ListView):
	template_name = "core/list_templates/blog.html"
	model = BlogPost
	paginate_by = 10

	def get_queryset(self):
		queryset = super(BlogListView, self).get_queryset()
		query = self.request.GET.get('search')
		if query:
			query_list = query.split('search')
			queryset = queryset.filter(
                reduce(operator.and_,
                       (Q(title__icontains=word) for word in query_list))|
                reduce(operator.and_,
                       (Q(sub_title__icontains=word) for word in query_list))|
                reduce(operator.and_,
                       (Q(content__icontains=word) for word in query_list))
            )
		return queryset

class BlogDetailView(DetailView):
	template_name = "core/detail_templates/blog_detail.html"
	model = BlogPost

class ServiceDetailView(DetailView):
	template_name = "core/detail_templates/service_detail.html"
	model = ServiceItem

class AboutInternalView(TemplateView):
    template_name = 'core/about.html'
    model = AboutInternal

    def get_context_data(self, **kwargs):
        context = super(AboutInternalView, self).get_context_data(**kwargs)
        context.update({
            'about_internal': AboutInternal.objects.all()
        })
        return context

core/templates/core/sections/about_section.html
{% load i18n %}
<!-- About Section -->
{% if about_section %}
<section class="page-section" id="about">
  {% for content in about_section %}
  <div class="container relative">
    <h2 class="section-title font-alt align-left mb-70 mb-sm-40">
      {{ content.title }}
    </h2>
    <div class="section-text mb-50 mb-sm-20">
      <div class="row">
        <div class="col-md-4">
          <blockquote>
            <p>
              {{ content.mention }}
            </p>
            <footer>
              {{ content.author }}
            </footer>
          </blockquote>
        </div>
        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
          {{ content.first_content|safe }}
        </div>
        <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
          {{ content.second_content|safe }}
        </div>
      </div>
    </div>
    <div class="align-center">
      <a href="{% url 'core:about' %}" class="section-more font-alt submit_btn btn btn-mod btn-medium btn-round">{% trans "Conheça o Instituto Beraca" %}</a>
    </div>
  </div>
  {% endfor %}
</section>
{% endif %}

core/templates/core/sections/blog_section.html
{% load staticfiles i18n %}

<!-- Blog Section -->
{% if posts %}
<section class="page-section" id="news">
    <div class="container relative">

        <h2 class="section-title font-alt align-left mb-70 mb-sm-40">
            {% trans "Notícias" %}

            <a href="{% url 'core:blog' %}" class="section-more right">{% trans "Veja todas as notícias" %} <i class="fa fa-angle-right"></i></a>

        </h2>

        <div class="row multi-columns-row">

            {% for post in posts %}
            <!-- Post Item -->
            <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">

                <div class="post-prev-img">
                    <a href="{% url 'core:post_detail' post.id %}"><img src="{{post.miniature.url}}" alt="{{post.title}}" /></a>
                </div>

                <div class="post-prev-title font-alt">
                    <a href="{% url 'core:post_detail' post.id %}">{{post.title}}</a>
                </div>

                <div class="post-prev-info font-alt">
                    <a href="">{{post.author}}</a> | {{post.date}}
                </div>

                <div class="post-prev-text">
                    {{post.intro}}
                </div>

                <div class="post-prev-more">
                    <a href="{% url 'core:post_detail' post.id %}" class="btn btn-mod btn-gray btn-round">{% trans "Leia mais" %}<i class="fa fa-angle-right"></i></a>
                </div>

            </div>
            {% endfor %}

        </div>

    </div>
</section>
<!-- End Blog Section -->
{% endif %}

core/templates/core/sections/call_section.html
{% load staticfiles i18n %}

<!-- Call Action Section -->

<section class="page-section pt-0 pb-0 banner-section bg-dark-alfa-30" data-background="{% static 'images/beraca_sementes.jpg' %}" id="portfolio">
  <div class="container relative">
    <div class="row">
      <div class="col-sm-6">
        <div class="mt-140 mt-lg-80 mb-140 mb-lg-80">
          <div class="banner-content">
            <h3 class="banner-heading font-alt">{% trans "Onde atuamos" %}</h3>
            <div class="banner-decription">
              {% trans "Atuamos em comunidades visando o desenvolvimento socioambiental." %}
            </div>
            <div class="local-scroll">
              <a href="{% url 'core:cases' %}" class="btn btn-mod btn-w btn-medium btn-round">{% trans "Veja nosso portfólio" %}</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

core/templates/core/sections/newsletter_section.html
{% load i18n %}
<!-- Newsletter Section -->
<section class="small-section bg-dark-alfa-30" data-background="{% static 'images/beraca_newsletter.jpg' %}">
  <div class="container relative">
    <form class="form align-center" id="mailchimp">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">

          <div class="newsletter-label font-alt">
            {% trans "Gostaria de receber nossa newsletter?" %}
          </div>
          <div class="mb-20">
            <input placeholder="Seu email" class="newsletter-field form-control input-md round mb-xs-10" type="email" pattern=".{5,100}" required/>
            <button type="submit" class="btn btn-mod btn-medium btn-round mb-xs-10">
              {% trans "Submeter" %}
            </button>
          </div>
          <div class="form-tip">
            <i class="fa fa-info-circle"></i> {% trans "Confie na gente, também não gostamos de spam." %}
          </div>
          <div id="subscribe-result"></div>
        </div>
      </div>
    </form>
  </div>
</section>
<!-- End Newsletter Section -->

core/templates/core/sections/services_section.html
{% load staticfiles i18n %}

<!-- Services Section -->
{% if services %}
<section class="page-section" id="services">
  <div class="container relative">
    <h2 class="section-title font-alt mb-70 mb-sm-40">
      {% trans "O que fazemos" %}
    </h2>
    <!-- Nav tabs -->

    <ul class="nav nav-tabs tpl-alt-tabs font-alt pt-30 pt-sm-0 pb-30 pb-sm-0">
      {% for service in services %}
      <li>
        <a href="#{{service.anchor}}" data-toggle="tab">
          <div class="alt-tabs-icon">
            <img src="{{service.icon.url}}" alt="{{service.title}}">
          </div>
          {{service.title}}
        </a>
      </li>
      {% endfor %}
    </ul>
    <!-- End Nav tabs -->
    <!-- Tab panes -->
    <div class="tab-content tpl-tabs-cont">
      <!-- Service Item -->
      {% for tab in tabs %}
      <div class="tab-pane fade" id="{{tab.anchor}}">
        <div class="section-text">
          <div class="row">
            <div class="col-md-4 mb-md-40 mb-xs-30">
              <blockquote class="mb-0">
                <p>
                  {{tab.mention}}
                </p>
                <footer>
                  {{tab.author}}
                </footer>
              </blockquote>
            </div>
            <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
              {{tab.abstract}}
            </div>
            <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
              {{tab.conclusion}}
            </div>

          </div>
        </div>
        <div class="align-center">
          <a href="{% url 'core:service_detail' tab.id %}" class="section-more font-alt submit_btn btn btn-mod btn-medium btn-round">{% trans "Conheça mais" %}</a>
        </div>
      </div>
      {% endfor %}
      <!-- End Service Item -->
    </div>
    <!-- End Tab panes -->
  </div>
</section>
{% endif %}
<!-- End Services Section -->