beraca/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('core.urls', namespace="core")),
]
# urlpatterns += i18n_patterns(
#     url(r'', include('core.urls', namespace="core")),
#     prefix_default_language=False,
# )

core/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import settings
from . import views
from django.views.generic.base import TemplateView

from django.contrib.sitemaps.views import sitemap

from core.views import AboutInternalView, ProjectView

from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^about/$', views.AboutInternalView.as_view(), name='about'),
    url(r'^apoieumprojeto/$', views.ProjectView.as_view(), name='project'),
    url(r'^cases/$', views.CasesView.as_view(), name='cases'),
    url(r'^cases/detail/(?P<pk>\d+)$', views.CaseDetailView.as_view(), name='detail'),
    url(r'^blog/$', views.BlogListView.as_view(), name='blog'),
    url(r'^blog/detail/(?P<pk>\d+)$', views.BlogDetailView.as_view(), name='post_detail'),
    url(r'^services/detail/(?P<pk>\d+)$', views.ServiceDetailView.as_view(), name='service_detail'),
    url(r'^robots.txt', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from ckeditor.fields import RichTextField

class Fullwidth_slider_item(models.Model):
    first_phrase = models.CharField("Primeira frase (menor)", max_length=50, blank=False)
    second_phrase = models.CharField("Segunda frase (em destaque)", max_length=50, blank=False)
    slide_image = models.ImageField("Imagem do slide", upload_to='slide_item/%Y/%m/%d/', blank=False)

    def __unicode__(self):
        return self.first_phrase+" "+self.second_phrase

    class Meta:
        verbose_name = "Slide"
        verbose_name_plural = "Slides"

def generate_filename_miniature(self, filename):
    url = "Cases/miniaturas/%s/%s" % (self.title, filename)
    return url

class PortfolioItem(models.Model):
    #common

    title = models.CharField("Título", max_length=300, blank=False)
    sub_title = models.CharField("Subtítulo", max_length=300, blank=False)

    study = models.TextField('Estudo do caso', blank=True)
    results = models.TextField("Resultado", blank=True)
    experience = models.TextField("Experiência", blank=True)

    client = models.CharField("Cliente", max_length=300, blank=False)
    date = models.DateField(auto_now=True)
    online = models.CharField("URL do cliente", max_length=500, blank=True)

    #miniature
    miniature = models.ImageField("Miniatura", upload_to=generate_filename_miniature, blank=False)
    tag = models.CharField("Tag para filtro", max_length=300, blank=False)
    lat = models.CharField("Latitude", max_length=100, blank=True)
    lon = models.CharField("Longitude", max_length=100, blank=True)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = PortfolioItem.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = PortfolioItem.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Portfolio/case"
        verbose_name_plural="Cases"
        ordering = ['-date']

def generate_filename(self, filename):
    url = "Portfolio/%s/%s" % (self.portfolio.title, filename)
    return url

class PortfolioImages(models.Model):
    portfolio = models.ForeignKey(PortfolioItem, related_name='images')
    image = models.ImageField("Primeira imagem(slide)", upload_to=generate_filename)

    def __unicode__(self):
        return self.portfolio.title

def generate_filename_miniature(self, filename):
    title = self.title[:20]
    url = "Posts/miniaturas/%s/%s" % (title, filename)
    return url

class BlogPost(models.Model):
    #common

    title = models.CharField("Título", max_length=300, blank=False)
    sub_title = models.CharField("Sub-título", max_length=300, blank=False, null=True)
    intro = models.TextField("Introdução", blank=False)
    content = RichTextField("Corpo do texto", blank=False)
    date = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)
    author = models.CharField("Autor", max_length=500, blank=True)

    #miniature
    miniature = models.ImageField("Miniatura", upload_to=generate_filename_miniature, blank=False, max_length=255)
    tag = models.CharField("Tag para filtro", max_length=300, blank=False)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = BlogPost.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = BlogPost.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Blog post"
        verbose_name_plural="Posts"
        ordering = ['-date']

def generate_filename(self, filename):
    title = self.post.title[:20]
    url = "Posts/%s/%s" % (title, filename)
    return url

class BlogImages(models.Model):
    post = models.ForeignKey(BlogPost, related_name='images')
    image = models.ImageField("Imagem", upload_to=generate_filename)

    def __unicode__(self):
        return self.post.title

def generate_filename(self, filename):
    url = "Service/%s/%s" % (self.title, filename)
    return url

class ServiceItem(models.Model):
    #common
    anchor = models.CharField("Âncora/Tab", max_length=300, blank=False)
    icon = models.ImageField("Ícone", upload_to=generate_filename)
    title = models.CharField("Título", max_length=300, blank=False)
    mention = models.TextField('Citação', blank=True)
    author = models.CharField("Autor", max_length=300, blank=False)
    abstract = models.TextField("Conceito", blank=True)
    conclusion = models.TextField("Conclusão", blank=True)
    description = RichTextField("Descrição", blank=True)
    date = models.DateField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = ServiceItem.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = ServiceItem.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Service/case"
        verbose_name_plural="Services"
        ordering = ['-date']


class ServiceIcons(models.Model):
    service = models.ForeignKey(ServiceItem, related_name='icones')
    icon = models.ImageField("Ícone", upload_to=generate_filename, blank=True)
    title = models.CharField("Título", max_length=300, blank=True)

    def __unicode__(self):
        return self.service.title

class ServiceMethod(models.Model):
    method = models.ForeignKey(ServiceItem, related_name='methods')
    image = models.ImageField("Imagem", upload_to=generate_filename, blank=True)
    title = models.CharField("Título", max_length=300, blank=True)
    desc = models.TextField("Descrição", max_length=1500, blank=True)

    def __unicode__(self):
        return self.method.title

class AboutSection(models.Model):
    title = models.CharField("Título", max_length=300, blank=True)
    mention = models.TextField('Citação', blank=True)
    author = models.CharField("Autor", max_length=300, blank=True)
    first_content = RichTextField("Primeiro Paragrafo", blank=True)
    second_content = RichTextField("Segundo Paragrafo", blank=True)

    class Meta:
        verbose_name = "Textos para seção 'Sobre'"
        verbose_name_plural = "Textos para seção 'Sobre'"

    def __unicode__(self):
        return self.title

class AboutInternal(models.Model):
    title = models.CharField("Título da Header", max_length=300, blank=True)
    subtitle = models.CharField("Subtítulo", max_length=300, blank=True)
    title_paragraph = models.CharField("Título do Paragrafo", max_length=300, blank=True)
    content = RichTextField("Descrição Geral", blank=True)
    director = RichTextField("Sobre diretoria", blank=True)
    council = RichTextField("Conselho Gestor", blank=True)
    mission = RichTextField("Missão", blank=True)
    vision = RichTextField("Visão", blank=True)
    values = RichTextField("Valores", blank=True)

    class Meta:
        verbose_name = "Textos para seção interna 'Sobre'"
        verbose_name_plural = "Textos para seção interna 'Sobre'"

    def __unicode__(self):
        return self.title

core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.mail import send_mail, BadHeaderError, EmailMessage
from django.conf import settings
from django.template.loader import get_template
from django.utils.translation import ugettext_lazy as _

class ContactUs(forms.Form):
    name = forms.CharField(required=False,
    widget=forms.TextInput(
    attrs={'class':'input-md round form-control', 'placeholder':_('NOME'), 'pattern':'.{3,100}', 'id':'name'}))

    email = forms.EmailField(required=False,
    widget=forms.TextInput(
        attrs={'class':'input-md round form-control', 'placeholder':'EMAIL', 'pattern':'.{5,100}', 'id':'email'}))

    content = forms.CharField(required=False,
    widget=forms.Textarea(
        attrs={'class':'input-md round form-control height-84', 'placeholder':_('MENSAGEM'), 'id':'message'}))

    def send_email(self):
        email_template = get_template('core/email_template.html')
        name = self.cleaned_data['name']
        from_email = self.cleaned_data['email']
        message = self.cleaned_data['content']
        context = {
            'name': name,
            'email': from_email,
            'message': message
        }
        html_email = email_template.render(context)
        subject = 'Novo Contato'
        try:
            email = EmailMessage(subject, html_email, from_email,[settings.EMAIL_TO])
            email.content_subtype = "html"
            email.send()
        except BadHeaderError:
            raise ValidationError("Cabeçalho inválido")

core/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse
from django.template.loader import get_template
from django.contrib import messages
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from .models import Fullwidth_slider_item, BlogPost, ServiceItem, AboutSection, PortfolioItem, AboutInternal
from .forms import *
import operator
from django.db.models import Q
from django.conf import settings
import urllib
import urllib2
import json
# from django.utils import translation


# Create your views here.
# def fullsite(request):
# 	context_general = {}
# 	return render(request, 'core/index.html', context_general)

class Index(FormView):
	template_name = "core/home.html"
	form_class = ContactUs
	success_url = '/'

	def get_context_data(self, **kwargs):
		context = super(Index, self).get_context_data(**kwargs)
		context.update({
			'slide_itens': Fullwidth_slider_item.objects.all(),
			'posts': BlogPost.objects.all().order_by('-date')[:3],
			'services': ServiceItem.objects.all().order_by('title')[:5],
			'tabs': ServiceItem.objects.all().order_by('-date')[:5],
			'about_section': AboutSection.objects.all(),
		})
		return context

	def form_valid(self, form):
		''' Begin reCAPTCHA validation '''
		recaptcha_response = self.request.POST.get('g-recaptcha-response')
		url = 'https://www.google.com/recaptcha/api/siteverify'
		values = {
			'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
			'response': recaptcha_response
        }
		data = urllib.urlencode(values)
		req = urllib2.Request(url, data)
		response = urllib2.urlopen(req)
		result = json.load(response)
		''' End reCAPTCHA validation '''
		print "hello"
		if result['success']:
			form.send_email()
			messages.success(self.request, 'Seu contato foi enviado com sucesso!')
		else:
			messages.error(self.request, 'reCAPTCHA inválida. Por favor, tente novamente.')

		return super(Index, self).form_valid(form)

	# from django.utils import translation
	# user_language = 'en'
	# translation.activate(user_language)
	# request.session[translation.LANGUAGE_SESSION_KEY] = user_language

	# if translation.LANGUAGE_SESSION_KEY in request.session:
	# 	del request.session[translation.LANGUAGE_SESSION_KEY]

class ProjectView(TemplateView):
    template_name = "core/project.html"

class CasesView(TemplateView):
	template_name = "core/cases.html"

	def get_context_data(self, **kwargs):
		context = super(CasesView, self).get_context_data(**kwargs)
		context.update({
			'cases': PortfolioItem.objects.all(),
		})
		return context

class CaseDetailView(DetailView):
	template_name = "core/detail_templates/case_detail.html"
	model = PortfolioItem


class BlogListView(ListView):
	template_name = "core/list_templates/blog.html"
	model = BlogPost
	paginate_by = 10

	def get_queryset(self):
		queryset = super(BlogListView, self).get_queryset()
		query = self.request.GET.get('search')
		if query:
			query_list = query.split('search')
			queryset = queryset.filter(
                reduce(operator.and_,
                       (Q(title__icontains=word) for word in query_list))|
                reduce(operator.and_,
                       (Q(sub_title__icontains=word) for word in query_list))|
                reduce(operator.and_,
                       (Q(content__icontains=word) for word in query_list))
            )
		return queryset

class BlogDetailView(DetailView):
	template_name = "core/detail_templates/blog_detail.html"
	model = BlogPost

class ServiceDetailView(DetailView):
	template_name = "core/detail_templates/service_detail.html"
	model = ServiceItem

class AboutInternalView(TemplateView):
    template_name = 'core/about.html'
    model = AboutInternal

    def get_context_data(self, **kwargs):
        context = super(AboutInternalView, self).get_context_data(**kwargs)
        context.update({
            'about_internal': AboutInternal.objects.all()
        })
        return context

core/templates/core/detail_templates/blog_detail.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block social_meta %}
    <meta property="og:title" content="{{ object.title }}" />
    {% for image in object.images.all%}
    <meta property="og:image" content="http://www.institutoberaca.org/{{ image.image.url }}" />
    {% endfor %}
    <meta property="og:url" content="http://www.institutoberaca.org{% url 'core:post_detail' object.id %}" />
    <meta property="og:site_name" content="Instituto Beraca"/>
    <meta property="og:description" content="{{object.intro}}">
    <meta property="og:type" content="article" />
    <meta property="og:locale" content="en_US" />
    <meta name="twitter:title" content="{{ object.title }}" />
    {% for image in object.images.all|slice:":10" %}
    <meta name="twitter:image" content="http://www.institutoberaca.org/{{ image.image.url }}" />
    {% endfor %}
    <meta name="twitter:url" content="http://www.institutoberaca.org/" />
    <meta name="twitter:card" content="" />
{% endblock social_meta %}

{% block content %}
  {% include 'core/partials/navpanel_with_links.html' %}
  {% include 'core/partials/blog_header.html' %}
  <!-- Section -->
  <section class="page-section">
    <div class="container relative">
      <div class="row">
        <!-- Content -->
        <div class="col-sm-10 col-sm-offset-1">
          <!-- Post -->
          <div class="blog-item mb-80 mb-xs-40">
            <!-- Text -->
            <div class="blog-item-body">
              <h1 class="mt-0 font-alt">{{object.title}}</h1>
              <div class="lead">
                <p>
                  {{object.sub_title}}
                </p>
              </div>
              <!-- End Text -->
              <!-- Media Gallery -->
              <div class="blog-media mt-40 mb-40 mb-xs-30">
                <ul class="clearlist content-slider">
                  {% for image in object.images.all%}
                  <li>
                    <img src="{{image.image.url}}" alt="{{object.title}}" />
                  </li>
                  {% endfor %}
                </ul>
              </div>
              <p>
                {{object.intro}}
              </p>
              <p>
                {{object.content|safe}}
              </p>
            </div>
            <!-- End Text -->
          </div>
          <!-- End Post -->
          <!-- Prev/Next Post -->
          <div class="clearfix mt-40">
            {% if object.get_prev %}
              <a href="{% url 'core:post_detail' object.get_prev.id %}" class="blog-item-more left"><button type="submit" class="submit_btn btn btn-mod btn-medium btn-round"><i class="fa fa-angle-left"></i>&nbsp;{% trans "Notícia anterior" %}</i></button></a>
            {% endif %}
            {% if object.get_next %}
              <a href="{% url 'core:post_detail' object.get_next.id %}" class="blog-item-more right"><button type="submit" class="submit_btn btn btn-mod btn-medium btn-round">{% trans "Próxima notícia" %}&nbsp;<i class="fa fa-angle-right"></i></button></a>
            {% endif %}
          </div>
          <!-- End Prev/Next Post -->
        </div>
        <!-- End Content -->
      </div>
    </div>
  </section>
  <!-- End Section -->
  {% block footer %}
    {{block.super}}
  {% endblock footer %}
{% endblock content %}

core/templates/core/detail_templates/case_detail.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block content %}
  {% block navigation %}
    {% include 'core/partials/navpanel.html' %}
  {% endblock navigation %}


  <section class="page-section bg-dark-alfa-30 parallax-3" data-background="{{object.images.all.0.image.url}}">
    <div class="relative container align-left">
      <div class="row">
        <div class="col-md-8">
          <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">{{object.title}}</h1>
          <div class="hs-line-4 font-alt">
            {{object.sub_title}}
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="page-section">
    <div class="container relative">
      <!-- Features Grid -->
      <div class="row alt-features-grid mb-80 mb-xs-40">
        <!-- Work Gallery -->
        <div class="work-full-media mb-80 mb-xs-40">
          <ul class="clearlist work-full-slider owl-carousel">
            {% for image in object.images.all %}
              <li>
                <img src="{{image.image.url}}" alt="{{object.title}}"/>
              </li>
            {% endfor %}
          </ul>
        </div>
        <!-- End Work Gallery -->
        <!-- Features Grid -->
        <div class="row multi-columns-row alt-features-grid mb-80 mb-xs-40">
          <!-- Features Item -->
          <div class="col-sm-6 col-md-4 col-lg-4">
            <div class="alt-features-item align-center">
              <h3 class="alt-features-title font-alt">1. {% trans "Estudo do caso" %}</h3>
              <div class="alt-features-descr align-left">
                {{object.study}}
              </div>
            </div>
          </div>
          <!-- End Features Item -->
          <!-- Features Item -->
          {% if object.results %}
            <div class="col-sm-6 col-md-4 col-lg-4">
              <div class="alt-features-item align-center">
                <h3 class="alt-features-title font-alt">2. {% trans "Resultado" %}</h3>
                <div class="alt-features-descr align-left">
                  {{object.results}}
                </div>
              </div>
            </div>
            <!-- End Features Item -->
          {% endif %}
          <!-- Features Item -->
          {% if object.experience %}
            <div class="col-sm-6 col-md-4 col-lg-4">
              <div class="alt-features-item align-center">
                <h3 class="alt-features-title font-alt">3. {% trans "Experiência" %}</h3>
                <div class="alt-features-descr align-left">
                  {{object.experience}}
                </div>
              </div>
            </div>
          {% endif %}
          <!-- End Features Item -->
        </div>
        <!-- Divider -->
        <hr class="mb-70 mb-xs-30"/>
        <!-- End Divider -->
        <div class="section-text mb-60 mb-sm-40">
          <div class="row">
            <div class="col-md-4 mb-sm-50 mb-xs-30">
              <!-- Project Detail -->
              <div class="work-detail">
                <h5 class="font-alt mt-0 mb-20">{% trans "Detalhes do projeto" %}</h5>
                <div class="work-full-detail">
                  <p>
                    <strong>{% trans "Cliente" %}:</strong>
                    {{object.client}}
                  </p>
                  <p>
                    <strong>{% trans "Data" %}:</strong>
                    {{object.date|date:"F"}}, {{object.date|date:"Y"}}
                  </p>
                </div>
              </div>
              <!-- End Project Detail -->
            </div>
            <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
            </div>
            <div class="col-md-4 col-sm-6 mb-sm-50 mb-xs-30">
            </div>
          </div>
        </div>
      </div>
    </section>
  <!-- End Section -->
  <!-- Divider -->
  <hr class="mt-0 mb-0 "/>
  <!-- End Divider -->
  <!-- Divider -->
  <hr class="mt-0 mb-0 "/>
  <!-- End Divider -->
  <!-- Work Navigation -->
  <div class="work-navigation clearfix">
    {% if object.get_prev %}
    <a href="{% url 'core:detail' object.get_prev.id %}" class="work-prev"><span><i class="fa fa-chevron-left"></i>&nbsp;{% trans "Case Anterior" %}</span></a>
    {% else %}
    <a class="work-prev">&nbsp;</a>
    {% endif %}
    <a href="{% url 'core:cases' %}" class="work-all"><span><i class="fa fa-times"></i>&nbsp;{% trans "Ver todos" %}</span></a>

    {% if object.get_next %}
    <a href="{% url 'core:detail' object.get_next.id %}" class="work-next"><span>{% trans "Próximo case" %}&nbsp;<i class="fa fa-chevron-right"></i></span></a>
    {% else %}
    <a class="work-prev">&nbsp;</a>
    {% endif %}
  </div>
  <!-- End Work Navigation -->
  <!-- Divider -->
  <hr class="mt-0 mb-0 "/>
  <!-- End Divider -->

  {% block footer %}
    {{block.super}}
  {% endblock footer %}
{% endblock content %}

core/templates/core/detail_templates/service_detail.html
{% extends 'core/base.html' %}
{% load staticfiles i18n %}

{% block content %}
  {% block navigation %}
    {% include 'core/partials/navpanel.html' %}
  {% endblock navigation %}

  <!-- Head Section -->
  <section class="page-section bg-dark-alfa-30 parallax-2" data-background="{% static 'images/oquefazemos.jpg' %}">
      <div class="relative container align-left">

          <div class="row">

              <div class="col-md-8">
                  <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">{% trans "O que fazemos" %}</h1>
                  <div class="hs-line-4 font-alt">
                      {% trans "Aproximamos realidades locais e oportunidades" %}
                  </div>
              </div>
          </div>

      </div>
  </section>
  <!-- End Head Section -->

  <!-- Features Section -->
  <section class="page-section">
      <div class="container relative">

          <!-- Features Grid -->
          <div class="row alt-features-grid mb-70 mb-xs-40">

              <!-- Text Item -->
              <div class="col-sm-8 col-sm-offset-2">
                  <div class="alt-features-item align-center">
                      <div class="alt-features-descr align-center">
                          <h4 class="mt-0 font-alt">{{ object.title}}</h4>
                          {{ object.description|safe}}
                      </div>
                  </div>
              </div>
          </div>
          <!-- End Text Item -->
          <div class="row alt-features-grid mb-70 mb-xs-40">
              {% for service in object.icones.all %}
              <!-- Features Item -->
              <div class="col-sm-3">
                  <div class="alt-features-item align-center">
                      <center class="alt-features-icon">
                          <img class="img-responsive" src="{{ service.icon.url }}">
                      </center>
                      <h3 class="alt-features-title font-alt">{{ service.title }}</h3>
                  </div>
              </div>
              <!-- End Features Item -->
              {% endfor %}
         </div>
         <!-- End Features Grid -->

         <!-- Divider -->
         <hr class="mb-70 mb-xs-30"/>
         <!-- End Divider -->

         <div class="row multi-columns-row">
              {% for method in object.methods.all %}
              <!-- Post Item -->
              <div class="col-sm-6 col-md-4 col-lg-4 mb-md-50 wow fadeIn" data-wow-delay="0.1s" data-wow-duration="2s">

                  <div class="post-prev-img">
                      <img src="{{ method.image.url }}" alt="{{ method.title }}" />
                  </div>

                  <div class="post-prev-title font-alt">
                      {{ method.title }}
                  </div>

                  <div class="post-prev-text">
                      {{ method.desc }}
                  </div>

              </div>
              <!-- End Post Item -->
              {% endfor %}
          </div>
      </div>
  </section>
  <!-- End Features Section -->


  <!-- Call Action Section -->
  <section class="page-section pt-0 pb-0 banner-section bg-dark-alfa-30" data-background="{% static 'images/beraca_sementes.jpg' %}" id="portfolio">
      <div class="container relative">

          <div class="row">

              <div class="col-sm-6">

                  <div class="mt-140 mt-lg-80 mb-140 mb-lg-80">
                      <div class="banner-content">
                          <h3 class="banner-heading font-alt">{% trans "Onde atuamos" %}</h3>
                          <div class="banner-decription">
                              {% trans "Atuamos em comunidades visando o desenvolvimento socioambiental." %}
                          </div>
                          <div class="local-scroll">
                              <a href="{% url 'core:cases' %}" class="btn btn-mod btn-w btn-medium btn-round">{% trans "Veja nosso portfólio" %}</a>
                          </div>
                      </div>
                  </div>

              </div>



          </div>

      </div>
  </section>
  <!-- End Call Action Section -->


  {% block footer %}
    {{block.super}}
  {% endblock footer %}
{% endblock content %}