beraca/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('core.urls', namespace="core")),
]
# urlpatterns += i18n_patterns(
#     url(r'', include('core.urls', namespace="core")),
#     prefix_default_language=False,
# )

core/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import settings
from . import views
from django.views.generic.base import TemplateView

from django.contrib.sitemaps.views import sitemap

from core.views import AboutInternalView, ProjectView

from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^about/$', views.AboutInternalView.as_view(), name='about'),
    url(r'^apoieumprojeto/$', views.ProjectView.as_view(), name='project'),
    url(r'^cases/$', views.CasesView.as_view(), name='cases'),
    url(r'^cases/detail/(?P<pk>\d+)$', views.CaseDetailView.as_view(), name='detail'),
    url(r'^blog/$', views.BlogListView.as_view(), name='blog'),
    url(r'^blog/detail/(?P<pk>\d+)$', views.BlogDetailView.as_view(), name='post_detail'),
    url(r'^services/detail/(?P<pk>\d+)$', views.ServiceDetailView.as_view(), name='service_detail'),
    url(r'^robots.txt', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from ckeditor.fields import RichTextField

class Fullwidth_slider_item(models.Model):
    first_phrase = models.CharField("Primeira frase (menor)", max_length=50, blank=False)
    second_phrase = models.CharField("Segunda frase (em destaque)", max_length=50, blank=False)
    slide_image = models.ImageField("Imagem do slide", upload_to='slide_item/%Y/%m/%d/', blank=False)

    def __unicode__(self):
        return self.first_phrase+" "+self.second_phrase

    class Meta:
        verbose_name = "Slide"
        verbose_name_plural = "Slides"

def generate_filename_miniature(self, filename):
    url = "Cases/miniaturas/%s/%s" % (self.title, filename)
    return url

class PortfolioItem(models.Model):
    #common

    title = models.CharField("Título", max_length=300, blank=False)
    sub_title = models.CharField("Subtítulo", max_length=300, blank=False)

    study = models.TextField('Estudo do caso', blank=True)
    results = models.TextField("Resultado", blank=True)
    experience = models.TextField("Experiência", blank=True)

    client = models.CharField("Cliente", max_length=300, blank=False)
    date = models.DateField(auto_now=True)
    online = models.CharField("URL do cliente", max_length=500, blank=True)

    #miniature
    miniature = models.ImageField("Miniatura", upload_to=generate_filename_miniature, blank=False)
    tag = models.CharField("Tag para filtro", max_length=300, blank=False)
    lat = models.CharField("Latitude", max_length=100, blank=True)
    lon = models.CharField("Longitude", max_length=100, blank=True)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = PortfolioItem.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = PortfolioItem.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Portfolio/case"
        verbose_name_plural="Cases"
        ordering = ['-date']

def generate_filename(self, filename):
    url = "Portfolio/%s/%s" % (self.portfolio.title, filename)
    return url

class PortfolioImages(models.Model):
    portfolio = models.ForeignKey(PortfolioItem, related_name='images')
    image = models.ImageField("Primeira imagem(slide)", upload_to=generate_filename)

    def __unicode__(self):
        return self.portfolio.title

def generate_filename_miniature(self, filename):
    title = self.title[:20]
    url = "Posts/miniaturas/%s/%s" % (title, filename)
    return url

class BlogPost(models.Model):
    #common

    title = models.CharField("Título", max_length=300, blank=False)
    sub_title = models.CharField("Sub-título", max_length=300, blank=False, null=True)
    intro = models.TextField("Introdução", blank=False)
    content = RichTextField("Corpo do texto", blank=False)
    date = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)
    author = models.CharField("Autor", max_length=500, blank=True)

    #miniature
    miniature = models.ImageField("Miniatura", upload_to=generate_filename_miniature, blank=False, max_length=255)
    tag = models.CharField("Tag para filtro", max_length=300, blank=False)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = BlogPost.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = BlogPost.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Blog post"
        verbose_name_plural="Posts"
        ordering = ['-date']

def generate_filename(self, filename):
    title = self.post.title[:20]
    url = "Posts/%s/%s" % (title, filename)
    return url

class BlogImages(models.Model):
    post = models.ForeignKey(BlogPost, related_name='images')
    image = models.ImageField("Imagem", upload_to=generate_filename)

    def __unicode__(self):
        return self.post.title

def generate_filename(self, filename):
    url = "Service/%s/%s" % (self.title, filename)
    return url

class ServiceItem(models.Model):
    #common
    anchor = models.CharField("Âncora/Tab", max_length=300, blank=False)
    icon = models.ImageField("Ícone", upload_to=generate_filename)
    title = models.CharField("Título", max_length=300, blank=False)
    mention = models.TextField('Citação', blank=True)
    author = models.CharField("Autor", max_length=300, blank=False)
    abstract = models.TextField("Conceito", blank=True)
    conclusion = models.TextField("Conclusão", blank=True)
    description = RichTextField("Descrição", blank=True)
    date = models.DateField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = ServiceItem.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = ServiceItem.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Service/case"
        verbose_name_plural="Services"
        ordering = ['-date']


class ServiceIcons(models.Model):
    service = models.ForeignKey(ServiceItem, related_name='icones')
    icon = models.ImageField("Ícone", upload_to=generate_filename, blank=True)
    title = models.CharField("Título", max_length=300, blank=True)

    def __unicode__(self):
        return self.service.title

class ServiceMethod(models.Model):
    method = models.ForeignKey(ServiceItem, related_name='methods')
    image = models.ImageField("Imagem", upload_to=generate_filename, blank=True)
    title = models.CharField("Título", max_length=300, blank=True)
    desc = models.TextField("Descrição", max_length=1500, blank=True)

    def __unicode__(self):
        return self.method.title

class AboutSection(models.Model):
    title = models.CharField("Título", max_length=300, blank=True)
    mention = models.TextField('Citação', blank=True)
    author = models.CharField("Autor", max_length=300, blank=True)
    first_content = RichTextField("Primeiro Paragrafo", blank=True)
    second_content = RichTextField("Segundo Paragrafo", blank=True)

    class Meta:
        verbose_name = "Textos para seção 'Sobre'"
        verbose_name_plural = "Textos para seção 'Sobre'"

    def __unicode__(self):
        return self.title

class AboutInternal(models.Model):
    title = models.CharField("Título da Header", max_length=300, blank=True)
    subtitle = models.CharField("Subtítulo", max_length=300, blank=True)
    title_paragraph = models.CharField("Título do Paragrafo", max_length=300, blank=True)
    content = RichTextField("Descrição Geral", blank=True)
    director = RichTextField("Sobre diretoria", blank=True)
    council = RichTextField("Conselho Gestor", blank=True)
    mission = RichTextField("Missão", blank=True)
    vision = RichTextField("Visão", blank=True)
    values = RichTextField("Valores", blank=True)

    class Meta:
        verbose_name = "Textos para seção interna 'Sobre'"
        verbose_name_plural = "Textos para seção interna 'Sobre'"

    def __unicode__(self):
        return self.title

core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.mail import send_mail, BadHeaderError, EmailMessage
from django.conf import settings
from django.template.loader import get_template
from django.utils.translation import ugettext_lazy as _

class ContactUs(forms.Form):
    name = forms.CharField(required=False,
    widget=forms.TextInput(
    attrs={'class':'input-md round form-control', 'placeholder':_('NOME'), 'pattern':'.{3,100}', 'id':'name'}))

    email = forms.EmailField(required=False,
    widget=forms.TextInput(
        attrs={'class':'input-md round form-control', 'placeholder':'EMAIL', 'pattern':'.{5,100}', 'id':'email'}))

    content = forms.CharField(required=False,
    widget=forms.Textarea(
        attrs={'class':'input-md round form-control height-84', 'placeholder':_('MENSAGEM'), 'id':'message'}))

    def send_email(self):
        email_template = get_template('core/email_template.html')
        name = self.cleaned_data['name']
        from_email = self.cleaned_data['email']
        message = self.cleaned_data['content']
        context = {
            'name': name,
            'email': from_email,
            'message': message
        }
        html_email = email_template.render(context)
        subject = 'Novo Contato'
        try:
            email = EmailMessage(subject, html_email, from_email,[settings.EMAIL_TO])
            email.content_subtype = "html"
            email.send()
        except BadHeaderError:
            raise ValidationError("Cabeçalho inválido")

core/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse
from django.template.loader import get_template
from django.contrib import messages
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from .models import Fullwidth_slider_item, BlogPost, ServiceItem, AboutSection, PortfolioItem, AboutInternal
from .forms import *
import operator
from django.db.models import Q
from django.conf import settings
import urllib
import urllib2
import json
# from django.utils import translation


# Create your views here.
# def fullsite(request):
# 	context_general = {}
# 	return render(request, 'core/index.html', context_general)

class Index(FormView):
	template_name = "core/home.html"
	form_class = ContactUs
	success_url = '/'

	def get_context_data(self, **kwargs):
		context = super(Index, self).get_context_data(**kwargs)
		context.update({
			'slide_itens': Fullwidth_slider_item.objects.all(),
			'posts': BlogPost.objects.all().order_by('-date')[:3],
			'services': ServiceItem.objects.all().order_by('title')[:5],
			'tabs': ServiceItem.objects.all().order_by('-date')[:5],
			'about_section': AboutSection.objects.all(),
		})
		return context

	def form_valid(self, form):
		''' Begin reCAPTCHA validation '''
		recaptcha_response = self.request.POST.get('g-recaptcha-response')
		url = 'https://www.google.com/recaptcha/api/siteverify'
		values = {
			'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
			'response': recaptcha_response
        }
		data = urllib.urlencode(values)
		req = urllib2.Request(url, data)
		response = urllib2.urlopen(req)
		result = json.load(response)
		''' End reCAPTCHA validation '''
		print "hello"
		if result['success']:
			form.send_email()
			messages.success(self.request, 'Seu contato foi enviado com sucesso!')
		else:
			messages.error(self.request, 'reCAPTCHA inválida. Por favor, tente novamente.')

		return super(Index, self).form_valid(form)

	# from django.utils import translation
	# user_language = 'en'
	# translation.activate(user_language)
	# request.session[translation.LANGUAGE_SESSION_KEY] = user_language

	# if translation.LANGUAGE_SESSION_KEY in request.session:
	# 	del request.session[translation.LANGUAGE_SESSION_KEY]

class ProjectView(TemplateView):
    template_name = "core/project.html"

class CasesView(TemplateView):
	template_name = "core/cases.html"

	def get_context_data(self, **kwargs):
		context = super(CasesView, self).get_context_data(**kwargs)
		context.update({
			'cases': PortfolioItem.objects.all(),
		})
		return context

class CaseDetailView(DetailView):
	template_name = "core/detail_templates/case_detail.html"
	model = PortfolioItem


class BlogListView(ListView):
	template_name = "core/list_templates/blog.html"
	model = BlogPost
	paginate_by = 10

	def get_queryset(self):
		queryset = super(BlogListView, self).get_queryset()
		query = self.request.GET.get('search')
		if query:
			query_list = query.split('search')
			queryset = queryset.filter(
                reduce(operator.and_,
                       (Q(title__icontains=word) for word in query_list))|
                reduce(operator.and_,
                       (Q(sub_title__icontains=word) for word in query_list))|
                reduce(operator.and_,
                       (Q(content__icontains=word) for word in query_list))
            )
		return queryset

class BlogDetailView(DetailView):
	template_name = "core/detail_templates/blog_detail.html"
	model = BlogPost

class ServiceDetailView(DetailView):
	template_name = "core/detail_templates/service_detail.html"
	model = ServiceItem

class AboutInternalView(TemplateView):
    template_name = 'core/about.html'
    model = AboutInternal

    def get_context_data(self, **kwargs):
        context = super(AboutInternalView, self).get_context_data(**kwargs)
        context.update({
            'about_internal': AboutInternal.objects.all()
        })
        return context

core/templates/core/about.html
{% extends 'core/base.html' %}
{% load staticfiles i18n %}

{% block content %}

{% include 'core/partials/navpanel_with_links.html' %}
{% if about_internal %}
<!-- Head Section -->
{% for content in about_internal %}
<section class="page-section bg-dark-alfa-30 parallax-2" data-background="{% static 'images/quemsomos.jpg' %}">

    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">{{ content.title }}</h1>
                <div class="hs-line-4 font-alt">
                    {{ content.subtitle }}
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Head Section -->
<!-- About Section -->
<section class="page-section" id="about">
    <div class="container relative">
        <div class="section-text mb-60 mb-sm-40">
            <div class="row">
                <center class="col-sm-8 col-sm-offset-2 mb-sm-50 mb-xs-30">
                    <h4 class="mt-0 font-alt">{{ content.title_paragraph }}</h4>
                    {{ content.content|safe }}
                </center>
            </div>
        </div>
    </div>
</section>
<!-- End About Section -->

<!-- Testimonials Section -->
<section class="page-section bg-color-alfa-30 team-core" data-background="{% static 'images/debora_goldemberg.jpg' %}">
  <div class="container absolute">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-12 mb-sm-30">
        <div class="team-item">
          <div class="team-item-detail">
            <div class="row">
                <!-- Col -->
                <div class="col-sm-8 col-sm-offset-2">
                  <!-- Nav Tabs -->
                    <div class="align-center mb-40 mb-xxs-30">
                      <ul class="nav nav-tabs tpl-minimal-tabs animate">
                        <li class="active">
                          <a href="#director" data-toggle="tab">{% trans "Direção" %}</a>
                        </li>
                        <li>
                          <a href="#council" data-toggle="tab">{% trans "Conselho Gestor" %}</a>
                        </li>
                      </ul>
                    </div>
                  <!-- End Nav Tabs -->
                  <!-- Tab panes -->
                    <div class="tab-content tpl-minimal-tabs-cont section-text align-center">
                      <div class="tab-pane fade in active" id="director">
                        {{ content.director|safe }}
                      </div>
                      <div class="tab-pane fade" id="council">
                        {{ content.council|safe }}
                      </div>
                    </div>
                  </div>
                  <!-- End Col -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</section>
<!-- End Testimonials Section -->

<!-- Divider -->
<hr class="mt-0 mb-0 "/>
<!-- End Divider -->
<!-- Story Section -->
<section class="page-section">
    <div class="container relative">
        <h2 class="section-title font-alt mb-70 mb-sm-40">
            {% trans "Conheça nosso ponto de vista" %}
        </h2>
        <!-- Our Story -->
        <div class="row">
            <!-- Col -->
            <div class="col-sm-8 col-sm-offset-2">
                <!-- Nav Tabs -->
                <div class="align-center mb-40 mb-xxs-30">
                    <ul class="nav nav-tabs tpl-minimal-tabs animate">
                        <li class="active">
                            <a href="#mini-one" data-toggle="tab">{% trans "Missão" %}</a>
                        </li>
                        <li>
                            <a href="#mini-two" data-toggle="tab">{% trans "Visão" %}</a>
                        </li>
                        <li>
                            <a href="#mini-three" data-toggle="tab">{% trans "Valores" %}</a>
                        </li>
                    </ul>
                </div>
                <!-- End Nav Tabs -->
                <!-- Tab panes -->
                <div class="tab-content tpl-minimal-tabs-cont section-text align-center">
                    <div class="tab-pane fade in active" id="mini-one">
                        {{ content.mission|safe }}
                    </div>
                    <div class="tab-pane fade" id="mini-two">
                      {{ content.vision|safe }}
		</div>
                    <div class="tab-pane fade" id="mini-three">

                      {{ content.values|safe }}
		</div>
                </div>
            </div>
            <!-- End Col -->
        </div>
        <!-- End Story -->
    </div>
</section>
<!-- End Story Section -->

<!-- Call Action Section -->
<section class="small-section bg-yellow-dg">
    <div class="container relative">

        <div class="align-center">
            <h3 class="banner-heading font-alt">{% trans "Quer conversar com a gente?" %}</h3>
            <div>
                <a href="{% url 'core:index' %}#contact" class="btn btn-mod btn-w btn-medium btn-round">{% trans "É rápido" %}</a>
            </div>
        </div>
    </div>
</section>
<!-- End Call Action Section -->
{% endfor %}
{% endif %}
{% block footer %}
  {{block.super}}
{% endblock footer %}

{% endblock content %}

core/templates/core/cases.html
{% extends 'core/base.html' %}
{% load staticfiles i18n %}

  {% block extrastyles %}
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.css' rel='stylesheet' />
    <style>
      body { margin:0; padding:0; }
      #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
  {% endblock extrastyles %}

{% block content %}
  {% include 'core/partials/navpanel_with_links.html' %}


  <!-- Head Section -->
  <section class="page-section bg-dark-alfa-30 parallax-3" data-background="{% static 'images/beraca_sementes.jpg' %}">
    <div class="relative container align-left">
      <div class="row">
        <div class="col-md-8">
          <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">{% trans "Portfólio de ações" %}</h1>
          <div class="hs-line-4 font-alt">
            {% trans "Atuamos com foco no desenvolvimento local sustentável" %}
          </div>
        </div>
      </div>
    </div>
  </div>
  </section>
  <!-- End Head Section -->
  <!-- Portfolio Section -->
  <section class="page-section">
    <div class="container relative">
      <!-- Map Section -->
	<iframe src="https://www.google.com/maps/d/embed?mid=1acO1dlXVfFnmrkozGzhummj7g-k" width="100%" height="400px"></iframe> <br><br>

<!--
      <div class="row">
        <div id='mapbox-control' class="col-md-7">
          <div id='map'></div>
        </div>
        <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoicnVpeiIsImEiOiJrVVcwQXFnIn0.6wBy9NLB7MVzx1_YMTHC6g';
        var map = new mapboxgl.Map({
          container: 'map', // container id
          style: 'mapbox://styles/ruiz/ciz9vm4m3004q2rnqesa11o4w', //stylesheet location
          center: [-58.253,-14.380], // starting position
          zoom: 2.9 // starting zoom
        });
        map.scrollZoom.disable();
        </script>
        <div id='mapbox-side' class="col-md-4">
          <h3 class="hs-line-11 font-alt mb-20 mb-xs-0">
            Conheça algumas áreas de atuação
          </h3>
        </div>
      </div> -->
      <!-- Works Filter -->
      <!--
      <div class="works-filter font-alt align-center">
        <a href="#" class="filter active" data-filter="*">Todos</a>
        <a href="#branding" class="filter" data-filter=".branding">Fundiária</a>
        <a href="#design" class="filter" data-filter=".design">Ambiental</a>
        <a href="#photography" class="filter" data-filter=".photography">Humanitária</a>
      </div> -->
      <!-- End Works Filter -->
      <!-- Works Grid -->
      <ul class="works-grid work-grid-2 work-grid-gut clearfix font-alt hover-white" id="work-grid">
        <!-- Work Item (Lightbox) -->
        {% for case in cases %}
        <li class="work-item mix photography">
          <a href="{% url 'core:detail' case.id %}" class="work-ext-link">
            <div class="work-img">
              <img src="{{case.miniature.url}}" alt="Work" />
            </div>
            <div class="work-intro">
              <h3 class="work-title">{{case.title}}</h3>
              <div class="work-descr">
                {{case.sub_title}}
              </div>
            </div>
          </a>
        </li>
        {% endfor %}
        <!-- End Work Item -->
        <!-- End Works Grid -->
      </div>
    </section>
    <!-- End Portfolio Section -->
    <!-- Call Action Section -->
    <section class="small-section bg-yellow-dg">
      <div class="container relative">
        <div class="align-center">
          <h3 class="banner-heading font-alt">{% trans "Gostou do nosso trabalho?" %}</h3>
          <div>
            <a href="{% url 'core:index' %}#contact" class="btn btn-mod btn-w btn-medium btn-round">{% trans "Converse conosco!" %}</a>
          </div>
        </div>
      </div>
    </section>
    <!-- End Call Action Section -->

    {% block footer %}
      {{block.super}}
    {% endblock footer %}

{% endblock content %}

{% block extrascripts %}
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAZsDkJFLS0b59q7cmW0EprwfcfUA8d9dg"></script>
{% endblock extrascripts %}

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}

  <!-- Fullwidth Slider -->
  {% block slider %}
    {% include 'core/partials/fullwidth_slider.html' %}
  {% endblock slider %}

  <!-- Navigation Menu -->
  {% block navigation %}
    {% include 'core/partials/navpanel.html' %}
  {% endblock navigation %}

  <!-- About Section -->
  {% block about %}
    {% include 'core/sections/about_section.html' %}
  {% endblock about %}

  <!-- Divider -->
  <hr class="mt-0 mb-0 "/>
  <!-- End Divider -->

  <!-- Services Section -->
  {% block services %}
    {% include 'core/sections/services_section.html' %}
  {% endblock services %}

  <!-- Call Action Section -->
  {% block call_actions %}
    {% include 'core/sections/call_section.html' %}
  {% endblock call_actions %}

  <!-- Blog Section -->
  {% block blog %}
    {% include 'core/sections/blog_section.html' %}
  {% endblock blog %}

  <!-- Contact Section -->
  {% block contact %}
    {% include 'core/sections/contact_section.html' %}
  {% endblock contact %}

  {# Footer#}
  {% block footer %}
    {{block.super}}
  {% endblock footer %}

{% endblock content %}

core/templates/core/maintenance.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block content %}
<article>
    <h1>{% trans "Estaremos de volta em breve!" %}</h1>
    <div>
        <p>{% trans "Descupe pelo inconveniente, mas nós estamos realizando uma manutenção no momento.
          Em breve estaremos de volta." %}
        <p>&mdash; Instituto Beraca</p>
    </div>
</article>
{% endblock %}

{% block extrastyles %}
<style>
  body { text-align: center; padding: 150px; }
  h1 { font-size: 50px; }
  body { font: 40px, sans-serif; color: #333; }
  article { display: block; text-align: left; width: 650px; margin: 0 auto; }
  a { color: #dc8100; text-decoration: none; }
  a:hover { color: #333; text-decoration: none; }
</style>
{% endblock extrastyles %}