beraca/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('core.urls', namespace="core")),
]
# urlpatterns += i18n_patterns(
#     url(r'', include('core.urls', namespace="core")),
#     prefix_default_language=False,
# )

core/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import settings
from . import views
from django.views.generic.base import TemplateView

from django.contrib.sitemaps.views import sitemap

from core.views import AboutInternalView, ProjectView

from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^about/$', views.AboutInternalView.as_view(), name='about'),
    url(r'^apoieumprojeto/$', views.ProjectView.as_view(), name='project'),
    url(r'^cases/$', views.CasesView.as_view(), name='cases'),
    url(r'^cases/detail/(?P<pk>\d+)$', views.CaseDetailView.as_view(), name='detail'),
    url(r'^blog/$', views.BlogListView.as_view(), name='blog'),
    url(r'^blog/detail/(?P<pk>\d+)$', views.BlogDetailView.as_view(), name='post_detail'),
    url(r'^services/detail/(?P<pk>\d+)$', views.ServiceDetailView.as_view(), name='service_detail'),
    url(r'^robots.txt', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from ckeditor.fields import RichTextField

class Fullwidth_slider_item(models.Model):
    first_phrase = models.CharField("Primeira frase (menor)", max_length=50, blank=False)
    second_phrase = models.CharField("Segunda frase (em destaque)", max_length=50, blank=False)
    slide_image = models.ImageField("Imagem do slide", upload_to='slide_item/%Y/%m/%d/', blank=False)

    def __unicode__(self):
        return self.first_phrase+" "+self.second_phrase

    class Meta:
        verbose_name = "Slide"
        verbose_name_plural = "Slides"

def generate_filename_miniature(self, filename):
    url = "Cases/miniaturas/%s/%s" % (self.title, filename)
    return url

class PortfolioItem(models.Model):
    #common

    title = models.CharField("Título", max_length=300, blank=False)
    sub_title = models.CharField("Subtítulo", max_length=300, blank=False)

    study = models.TextField('Estudo do caso', blank=True)
    results = models.TextField("Resultado", blank=True)
    experience = models.TextField("Experiência", blank=True)

    client = models.CharField("Cliente", max_length=300, blank=False)
    date = models.DateField(auto_now=True)
    online = models.CharField("URL do cliente", max_length=500, blank=True)

    #miniature
    miniature = models.ImageField("Miniatura", upload_to=generate_filename_miniature, blank=False)
    tag = models.CharField("Tag para filtro", max_length=300, blank=False)
    lat = models.CharField("Latitude", max_length=100, blank=True)
    lon = models.CharField("Longitude", max_length=100, blank=True)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = PortfolioItem.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = PortfolioItem.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Portfolio/case"
        verbose_name_plural="Cases"
        ordering = ['-date']

def generate_filename(self, filename):
    url = "Portfolio/%s/%s" % (self.portfolio.title, filename)
    return url

class PortfolioImages(models.Model):
    portfolio = models.ForeignKey(PortfolioItem, related_name='images')
    image = models.ImageField("Primeira imagem(slide)", upload_to=generate_filename)

    def __unicode__(self):
        return self.portfolio.title

def generate_filename_miniature(self, filename):
    title = self.title[:20]
    url = "Posts/miniaturas/%s/%s" % (title, filename)
    return url

class BlogPost(models.Model):
    #common

    title = models.CharField("Título", max_length=300, blank=False)
    sub_title = models.CharField("Sub-título", max_length=300, blank=False, null=True)
    intro = models.TextField("Introdução", blank=False)
    content = RichTextField("Corpo do texto", blank=False)
    date = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)
    author = models.CharField("Autor", max_length=500, blank=True)

    #miniature
    miniature = models.ImageField("Miniatura", upload_to=generate_filename_miniature, blank=False, max_length=255)
    tag = models.CharField("Tag para filtro", max_length=300, blank=False)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = BlogPost.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = BlogPost.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Blog post"
        verbose_name_plural="Posts"
        ordering = ['-date']

def generate_filename(self, filename):
    title = self.post.title[:20]
    url = "Posts/%s/%s" % (title, filename)
    return url

class BlogImages(models.Model):
    post = models.ForeignKey(BlogPost, related_name='images')
    image = models.ImageField("Imagem", upload_to=generate_filename)

    def __unicode__(self):
        return self.post.title

def generate_filename(self, filename):
    url = "Service/%s/%s" % (self.title, filename)
    return url

class ServiceItem(models.Model):
    #common
    anchor = models.CharField("Âncora/Tab", max_length=300, blank=False)
    icon = models.ImageField("Ícone", upload_to=generate_filename)
    title = models.CharField("Título", max_length=300, blank=False)
    mention = models.TextField('Citação', blank=True)
    author = models.CharField("Autor", max_length=300, blank=False)
    abstract = models.TextField("Conceito", blank=True)
    conclusion = models.TextField("Conclusão", blank=True)
    description = RichTextField("Descrição", blank=True)
    date = models.DateField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_next(self):
        next = ServiceItem.objects.filter(id__gt=self.id)
        if next:
          return next.first()
        return False

    def get_prev(self):
        prev = ServiceItem.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
          return prev.first()
        return False

    class Meta:
        verbose_name="Service/case"
        verbose_name_plural="Services"
        ordering = ['-date']


class ServiceIcons(models.Model):
    service = models.ForeignKey(ServiceItem, related_name='icones')
    icon = models.ImageField("Ícone", upload_to=generate_filename, blank=True)
    title = models.CharField("Título", max_length=300, blank=True)

    def __unicode__(self):
        return self.service.title

class ServiceMethod(models.Model):
    method = models.ForeignKey(ServiceItem, related_name='methods')
    image = models.ImageField("Imagem", upload_to=generate_filename, blank=True)
    title = models.CharField("Título", max_length=300, blank=True)
    desc = models.TextField("Descrição", max_length=1500, blank=True)

    def __unicode__(self):
        return self.method.title

class AboutSection(models.Model):
    title = models.CharField("Título", max_length=300, blank=True)
    mention = models.TextField('Citação', blank=True)
    author = models.CharField("Autor", max_length=300, blank=True)
    first_content = RichTextField("Primeiro Paragrafo", blank=True)
    second_content = RichTextField("Segundo Paragrafo", blank=True)

    class Meta:
        verbose_name = "Textos para seção 'Sobre'"
        verbose_name_plural = "Textos para seção 'Sobre'"

    def __unicode__(self):
        return self.title

class AboutInternal(models.Model):
    title = models.CharField("Título da Header", max_length=300, blank=True)
    subtitle = models.CharField("Subtítulo", max_length=300, blank=True)
    title_paragraph = models.CharField("Título do Paragrafo", max_length=300, blank=True)
    content = RichTextField("Descrição Geral", blank=True)
    director = RichTextField("Sobre diretoria", blank=True)
    council = RichTextField("Conselho Gestor", blank=True)
    mission = RichTextField("Missão", blank=True)
    vision = RichTextField("Visão", blank=True)
    values = RichTextField("Valores", blank=True)

    class Meta:
        verbose_name = "Textos para seção interna 'Sobre'"
        verbose_name_plural = "Textos para seção interna 'Sobre'"

    def __unicode__(self):
        return self.title

core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.mail import send_mail, BadHeaderError, EmailMessage
from django.conf import settings
from django.template.loader import get_template
from django.utils.translation import ugettext_lazy as _

class ContactUs(forms.Form):
    name = forms.CharField(required=False,
    widget=forms.TextInput(
    attrs={'class':'input-md round form-control', 'placeholder':_('NOME'), 'pattern':'.{3,100}', 'id':'name'}))

    email = forms.EmailField(required=False,
    widget=forms.TextInput(
        attrs={'class':'input-md round form-control', 'placeholder':'EMAIL', 'pattern':'.{5,100}', 'id':'email'}))

    content = forms.CharField(required=False,
    widget=forms.Textarea(
        attrs={'class':'input-md round form-control height-84', 'placeholder':_('MENSAGEM'), 'id':'message'}))

    def send_email(self):
        email_template = get_template('core/email_template.html')
        name = self.cleaned_data['name']
        from_email = self.cleaned_data['email']
        message = self.cleaned_data['content']
        context = {
            'name': name,
            'email': from_email,
            'message': message
        }
        html_email = email_template.render(context)
        subject = 'Novo Contato'
        try:
            email = EmailMessage(subject, html_email, from_email,[settings.EMAIL_TO])
            email.content_subtype = "html"
            email.send()
        except BadHeaderError:
            raise ValidationError("Cabeçalho inválido")

core/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse
from django.template.loader import get_template
from django.contrib import messages
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from .models import Fullwidth_slider_item, BlogPost, ServiceItem, AboutSection, PortfolioItem, AboutInternal
from .forms import *
import operator
from django.db.models import Q
from django.conf import settings
import urllib
import urllib2
import json
# from django.utils import translation


# Create your views here.
# def fullsite(request):
# 	context_general = {}
# 	return render(request, 'core/index.html', context_general)

class Index(FormView):
	template_name = "core/home.html"
	form_class = ContactUs
	success_url = '/'

	def get_context_data(self, **kwargs):
		context = super(Index, self).get_context_data(**kwargs)
		context.update({
			'slide_itens': Fullwidth_slider_item.objects.all(),
			'posts': BlogPost.objects.all().order_by('-date')[:3],
			'services': ServiceItem.objects.all().order_by('title')[:5],
			'tabs': ServiceItem.objects.all().order_by('-date')[:5],
			'about_section': AboutSection.objects.all(),
		})
		return context

	def form_valid(self, form):
		''' Begin reCAPTCHA validation '''
		recaptcha_response = self.request.POST.get('g-recaptcha-response')
		url = 'https://www.google.com/recaptcha/api/siteverify'
		values = {
			'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
			'response': recaptcha_response
        }
		data = urllib.urlencode(values)
		req = urllib2.Request(url, data)
		response = urllib2.urlopen(req)
		result = json.load(response)
		''' End reCAPTCHA validation '''
		print "hello"
		if result['success']:
			form.send_email()
			messages.success(self.request, 'Seu contato foi enviado com sucesso!')
		else:
			messages.error(self.request, 'reCAPTCHA inválida. Por favor, tente novamente.')

		return super(Index, self).form_valid(form)

	# from django.utils import translation
	# user_language = 'en'
	# translation.activate(user_language)
	# request.session[translation.LANGUAGE_SESSION_KEY] = user_language

	# if translation.LANGUAGE_SESSION_KEY in request.session:
	# 	del request.session[translation.LANGUAGE_SESSION_KEY]

class ProjectView(TemplateView):
    template_name = "core/project.html"

class CasesView(TemplateView):
	template_name = "core/cases.html"

	def get_context_data(self, **kwargs):
		context = super(CasesView, self).get_context_data(**kwargs)
		context.update({
			'cases': PortfolioItem.objects.all(),
		})
		return context

class CaseDetailView(DetailView):
	template_name = "core/detail_templates/case_detail.html"
	model = PortfolioItem


class BlogListView(ListView):
	template_name = "core/list_templates/blog.html"
	model = BlogPost
	paginate_by = 10

	def get_queryset(self):
		queryset = super(BlogListView, self).get_queryset()
		query = self.request.GET.get('search')
		if query:
			query_list = query.split('search')
			queryset = queryset.filter(
                reduce(operator.and_,
                       (Q(title__icontains=word) for word in query_list))|
                reduce(operator.and_,
                       (Q(sub_title__icontains=word) for word in query_list))|
                reduce(operator.and_,
                       (Q(content__icontains=word) for word in query_list))
            )
		return queryset

class BlogDetailView(DetailView):
	template_name = "core/detail_templates/blog_detail.html"
	model = BlogPost

class ServiceDetailView(DetailView):
	template_name = "core/detail_templates/service_detail.html"
	model = ServiceItem

class AboutInternalView(TemplateView):
    template_name = 'core/about.html'
    model = AboutInternal

    def get_context_data(self, **kwargs):
        context = super(AboutInternalView, self).get_context_data(**kwargs)
        context.update({
            'about_internal': AboutInternal.objects.all()
        })
        return context

core/templates/core/partials/blog_header.html
<!-- Head Section -->
{% load staticfiles i18n %}
<section class="page-section blog-header-background parallax-2" data-background="{% static 'images/noticias.jpg' %}">
  <div class="relative container align-left">
    <div class="row">
      <div class="col-md-8">
        <h1 class="hs-line-11 font-alt mb-20 mb-xs-0 white-text">{% trans "Notícias" %}</h1>
        <div class="hs-line-4 font-alt">
          {% trans "Aqui compartilhamos nossas melhores histórias" %}
        </div>
      </div>
    </div>
  </div>
</section>

core/templates/core/partials/footer.html
{% load staticfiles %}

<!-- ScrollDown section -->
<div class="container page-section">
  <div class="scrollDown">
  <a id='next' class="next"> <i class="fa fa-caret-down fa-4x" aria-hidden="true"></i></a>
  </div>
  <!-- end ScrollDown section -->
  <!-- Foter -->
  <footer class="page-section bg-gray-lighter footer pb-60">
    <!-- Footer Logo -->
    <div class="local-scroll mb-30 wow fadeInUp" data-wow-duration="1.2s">
      <a href="#top"><img src="{% static 'images/logo-beraca.svg' %}" width="78" height="36" alt="Instituto Beraca" /></a>
    </div>
    <!-- End Footer Logo -->
    <!-- Social Links -->
    <div class="footer-social-links mb-110 mb-xs-60">
      <a href="https://www.facebook.com/institutoberaca/" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a>
      <a href="https://www.instagram.com/institutoberaca/" title="Instagram" target="_blank"><i class="fa fa-instagram"></i></a>
    </div>
    <!-- End Social Links -->
    <!-- Footer Text -->
    <div class="footer-text">
      <!-- Copyright -->
      <center class="footer-copy font-alt">
        <a href="http://3ecologias.net/" target="_blank"><img class="img-responsive partner" src="{% static 'images/3e.png' %}" alt="3Ecologias"</a>
      </center>
      <!-- End Copyright -->
    </div>
    <!-- End Footer Text -->
  </div>
  <!-- Top Link -->
  <div class="local-scroll">
    <a href="#top" class="link-to-top"><i class="fa fa-caret-up"></i></a>
  </div>
  <!-- End Top Link -->
</footer>
<!-- End Foter -->

core/templates/core/partials/fullwidth_slider.html
{% load staticfiles i18n %}

<!-- Fullwidth Slider -->
<div class="home-section fullwidth-slider-fade bg-dark" id="home">
  <!-- Slide Item -->
  {% for slide in slide_itens %}
  <section class="home-section bg-scroll bg-dark-lighter" data-background="{{slide.slide_image.url}}">
      <div class="js-height-full container">
          <!-- Hero Content -->
          <div class="home-content">
              <div class="home-text">
                  <h1 class="hs-line-8 no-transp font-alt mb-50 mb-xs-30">
                      {{slide.first_phrase}}
                  </h1>

                  <h2 class="hs-line-14 font-alt mb-50 mb-xs-30">
                      {{slide.second_phrase}}
                  </h2>

                  <div class="local-scroll">
                      <a href="#about" class="btn btn-mod btn-border-w btn-medium btn-round hidden-xs">{% trans "Saiba mais" %}</a>
                    </div>
              </div>
          </div>
          <!-- End Hero Content -->
      </div>
  </section>
  <!-- End Slide Item -->
  {% endfor %}
</div>
<!-- End Fullwidth Slider -->

core/templates/core/partials/navpanel.html
{% load staticfiles %}
{% load i18n %}
<!-- Navigation panel -->
<nav class="main-nav white transparent stick-fixed">
  <div class="full-wrapper relative clearfix">
    <!-- Logo ( * your text or image into link tag *) -->
    <div class="nav-logo-wrap local-scroll">
      <a href="{% url 'core:index' %}" class="logo">
        <img src="{% static 'images/logo-beraca-horizontal.svg' %}" alt="Instituto Beraca" />
      </a>
    </div>
    <div class="mobile-nav">
      <i class="fa fa-bars"></i>
    </div>
    <!-- Main Menu -->
    <div class="inner-nav desktop-nav">
      <ul class="clearlist scroll-nav local-scroll">
        <li class="active"><a href="{% url 'core:index' %}#home">{% trans "Home" %}</a></li>
        <li><a href="{% url 'core:index' %}#about">{% trans "Quem somos" %}</a></li>
        <li><a href="{% url 'core:index' %}#services">{% trans "O que fazemos" %}</a></li>
        <li><a href="{% url 'core:index' %}#portfolio">{% trans "Onde atuamos" %}</a></li>
        <li><a href="{% url 'core:project' %}">{% trans "Apoie um projeto" %}</a></li>
        <li><a href="{% url 'core:index' %}#news">{% trans "Notícias" %}</a></li>
        <li><a href="{% url 'core:index' %}#contact">{% trans "Contatos" %}</a></li>
      </ul>
    </div>
    <button class="btn submit_btn btn-mod btn-lang" type="button" id="formButton"><i class="fa fa-globe fa-2x" aria-hidden="true"></i></button>
    <div class="form-lang">
      <form id="form-lang" class="form contact-form" action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{request.path}}" />
        <select name="language">
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          {% for language in languages %}
            <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
              {{ language.name_local }} ({{ language.code }})
          </option>
          {% endfor %}
        </select>
        <input class="btn submit_btn btn-mod" type="submit" value="Go" />
    </div>
  </div>

</nav>

<!-- End Navigation panel -->

core/templates/core/partials/navpanel_with_links.html
{% load staticfiles i18n %}
<!-- Navigation panel -->
<nav class="main-nav white transparent stick-fixed">
  <div class="full-wrapper relative clearfix">
    <!-- Logo ( * your text or image into link tag *) -->
    <div class="nav-logo-wrap local-scroll">
      <a href="{% url 'core:index' %}#top" class="logo">
        <img src="{% static 'images/logo-beraca-horizontal.svg' %}" alt="Instituto Beraca" />
      </a>
    </div>
    <div class="mobile-nav">
      <i class="fa fa-bars"></i>
    </div>
    <!-- Main Menu -->
    <div class="inner-nav desktop-nav">
      <ul class="clearlist scroll-nav local-scroll">
        <li class="active"><a href="{% url 'core:index' %}">{% trans "Home" %}</a></li>
        <li><a href="{% url 'core:index' %}#about">{% trans "Quem somos" %}</a></li>
        <li><a href="{% url 'core:index' %}#services">{% trans "O que fazemos" %}</a></li>
        <li><a href="{% url 'core:index' %}#portfolio">{% trans "Onde atuamos" %}</a></li>
        <li><a href="{% url 'core:project' %}">{% trans "Apoie um projeto" %}</a></li>
        <li><a href="{% url 'core:index' %}#news">{% trans "Notícias" %}</a></li>
        <li><a href="{% url 'core:index' %}#contact">{% trans "Contatos" %}</a></li>
      </ul>
    </div>
    <button class="btn submit_btn btn-mod btn-lang" type="button" id="formButton"><i class="fa fa-globe fa-2x" aria-hidden="true"></i></button>
    <div class="form-lang">
      <form id="form-lang" class="form contact-form" action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{request.path}}" />
        <select name="language">
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          {% for language in languages %}
            <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
              {{ language.name_local }} ({{ language.code }})
          </option>
          {% endfor %}
        </select>
        <input class="btn submit_btn btn-mod" type="submit" value="Go" />
    </div>
  </div>
</nav>
<!-- End Navigation panel -->